<?php
include_once("Model.php");
include_once("Brand.php");
include_once("Category.php");
include_once("Product.php");
include_once("Customer.php");
include_once("Image.php");
include_once("Cart.php");
include_once("Detail.php");
include_once("Order.php");
include_once("Admin.php");
include_once("Slider.php");
?>